{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"imdb_movies\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "imdb_movies",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "89d76b9e-0a25-4b4d-9126-55fbff33f9af",
            "sourceColumn": "id",
            "summarizeBy": "sum"
          },
          {
            "name": "título",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "86f455ec-148f-42e1-9c56-9190bda975cb",
            "sourceColumn": "título",
            "summarizeBy": "none"
          },
          {
            "name": "ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "82554c46-cfca-4942-bd45-3ce5997b1bbe",
            "sourceColumn": "ano",
            "summarizeBy": "sum"
          },
          {
            "name": "duração",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "32649d4b-b55f-4b68-949a-9c311b1e9126",
            "sourceColumn": "duração",
            "summarizeBy": "sum"
          },
          {
            "name": "nota_mpa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6228eced-9445-4127-8242-2b4e66eb4e08",
            "sourceColumn": "nota_mpa",
            "summarizeBy": "none"
          },
          {
            "name": "nota_imdb",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ef0327a8-277e-46de-8ba5-90508290a85c",
            "sourceColumn": "nota_imdb",
            "summarizeBy": "sum"
          },
          {
            "name": "voto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fcae5963-ff3a-418c-9f4b-3328a54d74b5",
            "sourceColumn": "voto",
            "summarizeBy": "sum"
          },
          {
            "name": "orçamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "6101f614-4702-408f-9d85-03939f1e08c1",
            "sourceColumn": "orçamento",
            "summarizeBy": "sum"
          },
          {
            "name": "receita_bruta_global",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "7ec09420-3d43-46bc-a579-be082511fb73",
            "sourceColumn": "receita_bruta_global",
            "summarizeBy": "sum"
          },
          {
            "name": "receita_bruta_us_canada",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "257b3c4b-a534-4bc3-9f4f-272ef3cf3cdf",
            "sourceColumn": "receita_bruta_us_canada",
            "summarizeBy": "sum"
          },
          {
            "name": "bruto_lançamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "abf580c4-9c6c-466c-825e-a657962cd5bd",
            "sourceColumn": "bruto_lançamento",
            "summarizeBy": "sum"
          },
          {
            "name": "diretor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fa412c63-451b-4292-b332-287bad688135",
            "sourceColumn": "diretor",
            "summarizeBy": "none"
          },
          {
            "name": "roteirista",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8b8edbf1-9cce-4f50-bf5a-2b1a57a783f3",
            "sourceColumn": "roteirista",
            "summarizeBy": "none"
          },
          {
            "name": "celebridade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b322987-7d2a-4abf-9cf5-e7116e036404",
            "sourceColumn": "celebridade",
            "summarizeBy": "none"
          },
          {
            "name": "gênero",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8f993ca-d2a7-4efb-bbd1-f7b6f8262140",
            "sourceColumn": "gênero",
            "summarizeBy": "none"
          },
          {
            "name": "país de origem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8bb4bad2-02f8-4f4e-b77c-4143fb67a42d",
            "sourceColumn": "país de origem",
            "summarizeBy": "none"
          },
          {
            "name": "local_de_filmagem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ab3f76b-6d69-4b97-a941-732f4287c4f8",
            "sourceColumn": "local_de_filmagem",
            "summarizeBy": "none"
          },
          {
            "name": "produtora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6283ba72-530b-4255-a27a-437813da48bd",
            "sourceColumn": "produtora",
            "summarizeBy": "none"
          },
          {
            "name": "idioma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af4c1a42-c6fd-4176-87d0-372f2b350743",
            "sourceColumn": "idioma",
            "summarizeBy": "none"
          },
          {
            "name": "indicações",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9cc1ed36-a5de-4270-b586-9f3ac8bbb092",
            "sourceColumn": "indicações",
            "summarizeBy": "sum"
          },
          {
            "name": "oscar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "af8601e8-1f40-4194-aeee-4cba2820bae4",
            "sourceColumn": "oscar",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "25b0ff42-aaf0-47a5-8fae-5770d7d81a15",
        "partitions": [
          {
            "name": "imdb_movies",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\lucas.patriota\\Downloads\\filmes_nova - world_imdb_movies_top_movies_per_year(1).csv\"),[Delimiter=\",\", Columns=24, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}, {\"Column7\", type text}, {\"Column8\", type text}, {\"Column9\", type text}, {\"Column10\", type text}, {\"Column11\", type text}, {\"Column12\", type text}, {\"Column13\", type text}, {\"Column14\", type text}, {\"Column15\", type text}, {\"Column16\", type text}, {\"Column17\", type text}, {\"Column18\", type text}, {\"Column19\", type text}, {\"Column20\", type text}, {\"Column21\", type text}, {\"Column22\", type text}, {\"Column23\", type text}, {\"Column24\", type text}}),",
                "    #\"2 Linhas Superiores Removidas\" = Table.Skip(#\"Tipo Alterado\",2),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"2 Linhas Superiores Removidas\", [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado1 (automático)\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"id\", type text}, {\"title\", type text}, {\"link\", type text}, {\"year\", Int64.Type}, {\"duration\", type text}, {\"rating_mpa\", type text}, {\"rating_imdb\", Int64.Type}, {\"vote\", Int64.Type}, {\"budget\", Int64.Type}, {\"gross_world_wide\", Int64.Type}, {\"gross_us_canada\", Currency.Type}, {\"gross_opening_weekend\", Int64.Type}, {\"director\", type text}, {\"writer\", type text}, {\"star\", type text}, {\"genre\", type text}, {\"country_origin\", type text}, {\"filming_location\", type text}, {\"production_company\", type text}, {\"language\", type text}, {\"captions\", type text}, {\"win\", Int64.Type}, {\"nomination\", Int64.Type}, {\"oscar\", Int64.Type}}),",
                "    #\"Últimos caracteres extraídos (remover leading tt)\" = Table.TransformColumns(#\"Tipo Alterado1 (automático)\", {{\"id\", each Text.End(_, 7), type text}}),",
                "    #\"Colunas Removidas (link)\" = Table.RemoveColumns(#\"Últimos caracteres extraídos (remover leading tt)\",{\"link\", \"captions\",\"win\"}),",
                "    #\"Colunas Renomeadas (todas)\" = Table.RenameColumns(#\"Colunas Removidas (link)\",{",
                "{\"title\", \"título\"},",
                "{\"year\",\"ano\"},",
                "{\"duration\",\"duração\"},",
                "{\"rating_mpa\",\"nota_mpa\"},",
                "{\"rating_imdb\",\"nota_imdb\"},",
                "{\"vote\",\"voto\"},",
                "{\"budget\",\"orçamento\"},",
                "{\"gross_world_wide\",\"receita_bruta_global\"},",
                "{\"gross_us_canada\",\"receita_bruta_us_canada\"},",
                "{\"director\",\"diretor\"},",
                "{\"writer\",\"roteirista\"},",
                "{\"gross_opening_weekend\",\"bruto_lançamento\"},",
                "{\"star\",\"celebridade\"},",
                "{\"genre\",\"gênero\"},",
                "{\"filming_location\",\"local_de_filmagem\"},",
                "{\"production_company\",\"produtora\"},",
                "{\"country_origin\",\"país de origem\"},",
                "{\"language\",\"idioma\"},",
                "{\"nomination\",\"indicações\"}",
                "",
                "}",
                "),",
                "    #\"Duplicatas Removidas (por id)\" = Table.Distinct(#\"Colunas Renomeadas (todas)\", {\"id\"}),",
                "    #\"Tipo Alterado2 (orçamento)\" = Table.TransformColumnTypes(#\"Duplicatas Removidas (por id)\",{{\"receita_bruta_global\", Currency.Type},{\"orçamento\", Currency.Type}}),",
                "    #\"Texto em Maiúscula (título)\" = Table.TransformColumns(#\"Tipo Alterado2 (orçamento)\",{{\"título\", Text.Upper, type text}}),",
                "    #\"Dividir Coluna por Delimitador (gênero, \"\",\"\")\" = Table.SplitColumn(#\"Texto em Maiúscula (título)\", \"gênero\", Splitter.SplitTextByEachDelimiter({\",\"}, QuoteStyle.Csv, false), {\"gênero.1\", \"gênero.2\"}),",
                "    #\"Tipos Alterados (automático)\" = Table.TransformColumnTypes(#\"Dividir Coluna por Delimitador (gênero, \"\",\"\")\",{{\"gênero.1\", type text}, {\"gênero.2\", type text}, {\"id\", Int64.Type}}),",
                "    #\"Colunas Removidas (gênero.2)\" = Table.RemoveColumns(#\"Tipos Alterados (automático)\",{\"gênero.2\"}),",
                "    #\"Colunas Renomeadas (gênero.1 -> gênero)\" = Table.RenameColumns(#\"Colunas Removidas (gênero.2)\",{{\"gênero.1\", \"gênero\"}}),",
                "    #\"Linhas Filtradas1 (nota_imdb nulas)\" = Table.SelectRows(#\"Colunas Renomeadas (gênero.1 -> gênero)\", each ([nota_imdb] <> null and [nota_imdb] <> \"\")),",
                "    #\"Dividir Coluna por Transição de Caractere1\" = Table.SplitColumn(#\"Linhas Filtradas1 (nota_imdb nulas)\", \"duração\", Splitter.SplitTextByCharacterTransition({\"0\"..\"9\"}, (c) => not List.Contains({\"0\"..\"9\"}, c)), {\"duração.1\", \"duração.2\", \"duração.3\"}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Dividir Coluna por Transição de Caractere1\",\"1\",\"60\",Replacer.ReplaceValue,{\"duração.1\"}),",
                "    #\"Valor Substituído1\" = Table.ReplaceValue(#\"Valor Substituído\",\"2\",\"120\",Replacer.ReplaceValue,{\"duração.1\"}),",
                "    #\"Valor Substituído2\" = Table.ReplaceValue(#\"Valor Substituído1\",\"3\",\"180\",Replacer.ReplaceValue,{\"duração.1\"}),",
                "    #\"Valor Substituído3\" = Table.ReplaceValue(#\"Valor Substituído2\",\"4\",\"240\",Replacer.ReplaceValue,{\"duração.1\"}),",
                "    #\"Dividir Coluna por Delimitador\" = Table.SplitColumn(#\"Valor Substituído3\", \"duração.2\", Splitter.SplitTextByDelimiter(\" \", QuoteStyle.Csv), {\"duração.2.1\", \"duração.2.2\"}),",
                "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(#\"Dividir Coluna por Delimitador\",{{\"duração.2.1\", type text}, {\"duração.2.2\", Int64.Type}, {\"duração.3\", type text}, {\"duração.1\", Int64.Type}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado2\",{\"duração.2.1\"}),",
                "    #\"Tipo Alterado3\" = Table.TransformColumnTypes(#\"Colunas Removidas\",{{\"duração.1\", Int64.Type}}),",
                "    #\"Colunas Removidas2\" = Table.RemoveColumns(#\"Tipo Alterado3\",{\"duração.3\"}),",
                "    #\"Erros Substituídos\" = Table.ReplaceErrorValues(#\"Colunas Removidas2\", {{\"duração.1\", 0}}),",
                "    #\"Linhas Classificadas\" = Table.Sort(#\"Erros Substituídos\",{{\"duração.1\", Order.Descending}}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Linhas Classificadas\", \"Personalizar\", each [duração.1]+[duração.2.2]),",
                "    #\"Colunas Reordenadas\" = Table.ReorderColumns(#\"Personalização Adicionada\",{\"id\", \"título\", \"ano\", \"duração.1\", \"duração.2.2\", \"Personalizar\", \"nota_mpa\", \"nota_imdb\", \"voto\", \"orçamento\", \"receita_bruta_global\", \"receita_bruta_us_canada\", \"bruto_lançamento\", \"diretor\", \"roteirista\", \"celebridade\", \"gênero\", \"país de origem\", \"local_de_filmagem\", \"produtora\", \"idioma\", \"indicações\", \"oscar\"}),",
                "    #\"Colunas Renomeadas (DURAÇÃO)\" = Table.RenameColumns(#\"Colunas Reordenadas\",{{\"Personalizar\", \"duração\"}, {\"duração.1\", \"duração.horas\"}, {\"duração.2.2\", \"duração.minutos\"}}),",
                "    #\"Colunas Removidas1 (DURAÇÃO rascunhos)\" = Table.RemoveColumns(#\"Colunas Renomeadas (DURAÇÃO)\",{\"duração.horas\", \"duração.minutos\"}),",
                "    #\"Tipo Alterado1 (duração -> int64)\" = Table.TransformColumnTypes(#\"Colunas Removidas1 (DURAÇÃO rascunhos)\",{{\"duração\", Int64.Type}}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Tipo Alterado1 (duração -> int64)\", each ([local_de_filmagem] = \"\")),",
                "    #\"falsos nulos\" = Table.ReplaceValue(#\"Linhas Filtradas\",\"\",null,Replacer.ReplaceValue,{\"local_de_filmagem\"})",
                "in",
                "    #\"falsos nulos\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_75812958-41e0-491a-a353-da749a179cbe",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "42a0c361-4388-4b6f-8bd6-16b272aa9d87",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d33fb36e-52a9-4a8a-b5c9-862355c2ef25",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c51d7991-8049-4a0f-a491-43b71b999da3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "627de7c5-f011-4f30-8a19-429159380f3b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "154a353f-993b-4521-abdb-af213f6e95c0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "78583547-894f-45a4-aa7d-2762687551fa",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "edfdd024-c864-4843-8c5f-3d7eb6ab74dc",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "8b8ca500-0716-46c7-8211-809d1f5e921b",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "8e9533a1-2070-4053-8764-ab4522f801eb",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "a5ca8577-a895-4b1a-ab09-9bb2ce63d9e4",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "66f494f2-1b0c-4c7b-8108-8605930804b2",
                "ordinal": 3
              }
            ],
            "lineageTag": "a402ef20-6182-48fc-8d59-b1d28ad8aa24"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "6671a6a2-b5a0-4b7b-b59a-1c845680874c",
        "partitions": [
          {
            "name": "DateTableTemplate_75812958-41e0-491a-a353-da749a179cbe",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}