table imdb_movies
	lineageTag: 25b0ff42-aaf0-47a5-8fae-5770d7d81a15

	measure 'Total de Filmes' = COUNTROWS(imdb_movies)
		formatString: 0
		lineageTag: 1f6b25a1-8ba3-4fbe-9d9d-f47e67dcc240

	measure 'Media De Nota IMDB pós Anos 2000' =
			CALCULATE(
			    AVERAGE(imdb_movies[nota_imdb]),
			    imdb_movies[ano] >= 2000
			    )
		lineageTag: 030d7ea4-225b-4730-8fa8-bf49bc7637d9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Resultado Financeiro Total' = ```
			
			SUMX(
			    'imdb_movies', 
			    'imdb_movies'[receita_bruta_global] - 'imdb_movies'[orçamento]
			)
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: f8bb84f9-5813-4c17-a547-ae943d21cd48

	column id
		dataType: int64
		formatString: 0
		lineageTag: 89d76b9e-0a25-4b4d-9126-55fbff33f9af
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column título
		dataType: string
		lineageTag: 86f455ec-148f-42e1-9c56-9190bda975cb
		summarizeBy: none
		sourceColumn: título

		annotation SummarizationSetBy = Automatic

	column ano
		dataType: int64
		formatString: 0
		lineageTag: 82554c46-cfca-4942-bd45-3ce5997b1bbe
		summarizeBy: sum
		sourceColumn: ano

		annotation SummarizationSetBy = Automatic

	column duração
		dataType: int64
		formatString: 0
		lineageTag: 32649d4b-b55f-4b68-949a-9c311b1e9126
		summarizeBy: sum
		sourceColumn: duração

		annotation SummarizationSetBy = Automatic

	column nota_mpa
		dataType: string
		lineageTag: 6228eced-9445-4127-8242-2b4e66eb4e08
		summarizeBy: none
		sourceColumn: nota_mpa

		annotation SummarizationSetBy = Automatic

	column nota_imdb
		dataType: int64
		formatString: 0
		lineageTag: ef0327a8-277e-46de-8ba5-90508290a85c
		summarizeBy: sum
		sourceColumn: nota_imdb

		annotation SummarizationSetBy = Automatic

	column voto
		dataType: int64
		formatString: 0
		lineageTag: fcae5963-ff3a-418c-9f4b-3328a54d74b5
		summarizeBy: sum
		sourceColumn: voto

		annotation SummarizationSetBy = Automatic

	column orçamento
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 6101f614-4702-408f-9d85-03939f1e08c1
		summarizeBy: sum
		sourceColumn: orçamento

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column receita_bruta_global
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 7ec09420-3d43-46bc-a579-be082511fb73
		summarizeBy: sum
		sourceColumn: receita_bruta_global

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column receita_bruta_us_canada
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 257b3c4b-a534-4bc3-9f4f-272ef3cf3cdf
		summarizeBy: sum
		sourceColumn: receita_bruta_us_canada

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column bruto_lançamento
		dataType: int64
		formatString: 0
		lineageTag: abf580c4-9c6c-466c-825e-a657962cd5bd
		summarizeBy: sum
		sourceColumn: bruto_lançamento

		annotation SummarizationSetBy = Automatic

	column diretor
		dataType: string
		lineageTag: fa412c63-451b-4292-b332-287bad688135
		summarizeBy: none
		sourceColumn: diretor

		annotation SummarizationSetBy = Automatic

	column roteirista
		dataType: string
		lineageTag: 8b8edbf1-9cce-4f50-bf5a-2b1a57a783f3
		summarizeBy: none
		sourceColumn: roteirista

		annotation SummarizationSetBy = Automatic

	column celebridade
		dataType: string
		lineageTag: 9b322987-7d2a-4abf-9cf5-e7116e036404
		summarizeBy: none
		sourceColumn: celebridade

		annotation SummarizationSetBy = Automatic

	column gênero
		dataType: string
		lineageTag: a8f993ca-d2a7-4efb-bbd1-f7b6f8262140
		summarizeBy: none
		sourceColumn: gênero

		annotation SummarizationSetBy = Automatic

	column 'país de origem'
		dataType: string
		lineageTag: 8bb4bad2-02f8-4f4e-b77c-4143fb67a42d
		summarizeBy: none
		sourceColumn: país de origem

		annotation SummarizationSetBy = Automatic

	column produtora
		dataType: string
		lineageTag: 6283ba72-530b-4255-a27a-437813da48bd
		summarizeBy: none
		sourceColumn: produtora

		annotation SummarizationSetBy = Automatic

	column idioma
		dataType: string
		lineageTag: af4c1a42-c6fd-4176-87d0-372f2b350743
		summarizeBy: none
		sourceColumn: idioma

		annotation SummarizationSetBy = Automatic

	column indicações
		dataType: int64
		formatString: 0
		lineageTag: 9cc1ed36-a5de-4270-b586-9f3ac8bbb092
		summarizeBy: sum
		sourceColumn: indicações

		annotation SummarizationSetBy = Automatic

	column oscar
		dataType: int64
		formatString: 0
		lineageTag: af8601e8-1f40-4194-aeee-4cba2820bae4
		summarizeBy: sum
		sourceColumn: oscar

		annotation SummarizationSetBy = Automatic

	column classificacao_duracao
		dataType: string
		lineageTag: 26858abe-6f73-482e-b05d-896919db40c4
		summarizeBy: none
		sourceColumn: classificacao_duracao

		annotation SummarizationSetBy = Automatic

	column local_de_filmagem
		dataType: string
		lineageTag: 7ed5c5ce-ab5f-4162-abb7-8b95d845dd13
		summarizeBy: none
		sourceColumn: local_de_filmagem

		annotation SummarizationSetBy = Automatic

	column status_de_critica = ```
			IF([nota_imdb] > 80, "Excelente", "Comum") 
			```
		lineageTag: 5d14af8e-9252-4012-a6e6-82eb0f934307
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition imdb_movies = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\mailp\OneDrive\Documents\projeto_imdb-main\arquivos_fornecidos\filmes_nova - world_imdb_movies_top_movies_per_year.csv"),[Delimiter=",", Columns=24, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"PASSO 0 [AUTO] - Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type text}, {"Column23", type text}, {"Column24", type text}}),
				    #"PASSO 7 - 2 Linhas Superiores Removidas" = Table.Skip(#"PASSO 0 [AUTO] - Tipo Alterado",2),
				    #"PASSO 7 - Cabeçalhos Promovidos" = Table.PromoteHeaders(#"PASSO 7 - 2 Linhas Superiores Removidas", [PromoteAllScalars=true]),
				    #"PASSO 0 [AUTO] - Tipos Alterados - (automático)" = Table.TransformColumnTypes(#"PASSO 7 - Cabeçalhos Promovidos",{{"id", type text}, {"title", type text}, {"link", type text}, {"year", Int64.Type}, {"duration", type text}, {"rating_mpa", type text}, {"rating_imdb", Int64.Type}, {"vote", Int64.Type}, {"budget", Int64.Type}, {"gross_world_wide", Int64.Type}, {"gross_us_canada", Currency.Type}, {"gross_opening_weekend", Int64.Type}, {"director", type text}, {"writer", type text}, {"star", type text}, {"genre", type text}, {"country_origin", type text}, {"filming_location", type text}, {"production_company", type text}, {"language", type text}, {"captions", type text}, {"win", Int64.Type}, {"nomination", Int64.Type}, {"oscar", Int64.Type}}),
				    #"PASSO 8 - Colunas Removidas (link)" = Table.RemoveColumns(#"PASSO 0 [AUTO] - Tipos Alterados - (automático)",{"link", "captions","win"}),
				    #"PASSO 9 - Últimos caracteres extraídos (remover leading tt)" = Table.TransformColumns(#"PASSO 8 - Colunas Removidas (link)", {{"id", each Text.End(_, 7), type text}}),
				    #"PASSO 9 - Duplicatas Removidas (por id)" = Table.Distinct(#"PASSO 9 - Últimos caracteres extraídos (remover leading tt)", {"id"}),
				    #"PASSO 10 - Colunas Renomeadas (todas)" = Table.RenameColumns(#"PASSO 9 - Duplicatas Removidas (por id)",{
				{"title", "título"},
				{"year","ano"},
				{"duration","duração"},
				{"rating_mpa","nota_mpa"},
				{"rating_imdb","nota_imdb"},
				{"vote","voto"},
				{"budget","orçamento"},
				{"gross_world_wide","receita_bruta_global"},
				{"gross_us_canada","receita_bruta_us_canada"},
				{"director","diretor"},
				{"writer","roteirista"},
				{"gross_opening_weekend","bruto_lançamento"},
				{"star","celebridade"},
				{"genre","gênero"},
				{"filming_location","local_de_filmagem"},
				{"production_company","produtora"},
				{"country_origin","país de origem"},
				{"language","idioma"},
				{"nomination","indicações"}
				
				}
				),
				    #"PASSO 11 - Tipo Alterado2 (orçamento)" = Table.TransformColumnTypes(#"PASSO 10 - Colunas Renomeadas (todas)",{{"receita_bruta_global", Currency.Type},{"orçamento", Currency.Type}}),
				    #"PASSO 12 - Texto em Maiúscula (título)" = Table.TransformColumns(#"PASSO 11 - Tipo Alterado2 (orçamento)",{{"título", Text.Upper, type text}}),
				    #"PASSO 13 - Dividir Coluna por Delimitador (gênero, "","")" = Table.SplitColumn(#"PASSO 12 - Texto em Maiúscula (título)", "gênero", Splitter.SplitTextByEachDelimiter({","}, QuoteStyle.Csv, false), {"gênero.1", "gênero.2"}),
				    #"PASSO 13 - Tipos Alterados (automático)" = Table.TransformColumnTypes(#"PASSO 13 - Dividir Coluna por Delimitador (gênero, "","")",{{"gênero.1", type text}, {"gênero.2", type text}, {"id", Int64.Type}}),
				    #"PASSO 13 - Colunas Removidas (gênero.2)" = Table.RemoveColumns(#"PASSO 13 - Tipos Alterados (automático)",{"gênero.2"}),
				    #"PASSO 13 - Colunas Renomeadas (gênero.1 -> gênero)" = Table.RenameColumns(#"PASSO 13 - Colunas Removidas (gênero.2)",{{"gênero.1", "gênero"}}),
				    #"PASSO 14 - Linhas Filtradas1 (nota_imdb nulas)" = Table.SelectRows(#"PASSO 13 - Colunas Renomeadas (gênero.1 -> gênero)", each ([nota_imdb] <> null and [nota_imdb] <> "")),
				    #"PASSO 15 - Dividir Coluna de duração baseado em dígito/não dígito" = Table.SplitColumn(#"PASSO 14 - Linhas Filtradas1 (nota_imdb nulas)", "duração", Splitter.SplitTextByCharacterTransition({"0".."9"}, (c) => not List.Contains({"0".."9"}, c)), {"duração.1", "duração.2", "duração.3"}),
				    #"PASSO 15 - Valor Substituído [1 (h) equivale a 60(min)]" = Table.ReplaceValue(#"PASSO 15 - Dividir Coluna de duração baseado em dígito/não dígito","1","60",Replacer.ReplaceValue,{"duração.1"}),
				    #"PASSO 15 - Valor Substituído1 [2 (h) equivale a 120(min)]" = Table.ReplaceValue(#"PASSO 15 - Valor Substituído [1 (h) equivale a 60(min)]","2","120",Replacer.ReplaceValue,{"duração.1"}),
				    #"PASSO 15 - Valor Substituído2 [3 (h) equivale a 180(min)]" = Table.ReplaceValue(#"PASSO 15 - Valor Substituído1 [2 (h) equivale a 120(min)]","3","180",Replacer.ReplaceValue,{"duração.1"}),
				    #"PASSO 15 - Valor Substituído3 [4 (h) equivale a 240(min)]" = Table.ReplaceValue(#"PASSO 15 - Valor Substituído2 [3 (h) equivale a 180(min)]","4","240",Replacer.ReplaceValue,{"duração.1"}),
				    #"PASSO 15 - Dividir Coluna por Delimitador (Extrair ""m"" da coluna de minutos)" = Table.SplitColumn(#"PASSO 15 - Valor Substituído3 [4 (h) equivale a 240(min)]", "duração.2", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), {"duração.2.1", "duração.2.2"}),
				    #"PASSO 15 - Colunas de duração como Int64" = Table.TransformColumnTypes(#"PASSO 15 - Dividir Coluna por Delimitador (Extrair ""m"" da coluna de minutos)",{{"duração.2.1", type text}, {"duração.2.2", Int64.Type}, {"duração.3", type text}, {"duração.1", Int64.Type}}),
				    #"PASSO 15 - Colunas Removidas (coluna com string 'm' e coluna com string 'h')" = Table.RemoveColumns(#"PASSO 15 - Colunas de duração como Int64",{"duração.2.1", "duração.3"}),
				    #"PASSO 15 - Erros Substituídos (Colunas que continham valores de classificação indicativa em duração)" = Table.ReplaceErrorValues(#"PASSO 15 - Colunas Removidas (coluna com string 'm' e coluna com string 'h')", {{"duração.1", 0}}),
				    #"PASSO 15 - Somar a coluna de hora convertida à de minutos" = Table.AddColumn(#"PASSO 15 - Erros Substituídos (Colunas que continham valores de classificação indicativa em duração)", "Personalizar", each [duração.1]+[duração.2.2]),
				    #"PASSO 15 - Colunas Reordenadas" = Table.ReorderColumns(#"PASSO 15 - Somar a coluna de hora convertida à de minutos",{"id", "título", "ano", "duração.1", "duração.2.2", "Personalizar", "nota_mpa", "nota_imdb", "voto", "orçamento", "receita_bruta_global", "receita_bruta_us_canada", "bruto_lançamento", "diretor", "roteirista", "celebridade", "gênero", "país de origem", "local_de_filmagem", "produtora", "idioma", "indicações", "oscar"}),
				    #"PASSO 15 - Colunas Renomeadas (DURAÇÃO)" = Table.RenameColumns(#"PASSO 15 - Colunas Reordenadas",{{"Personalizar", "duração"}, {"duração.1", "duração.horas"}, {"duração.2.2", "duração.minutos"}}),
				    #"PASSO 15 - Colunas Removidas (duração.minutos e duração.horas)" = Table.RemoveColumns(#"PASSO 15 - Colunas Renomeadas (DURAÇÃO)",{"duração.horas", "duração.minutos"}),
				    #"PASSO 15 - Tipo Alterado (duração -> int64)" = Table.TransformColumnTypes(#"PASSO 15 - Colunas Removidas (duração.minutos e duração.horas)",{{"duração", Int64.Type}}),
				    #"PASSO 16 - Falsos nulos" = Table.ReplaceValue(#"PASSO 15 - Tipo Alterado (duração -> int64)","",null,Replacer.ReplaceValue,{"local_de_filmagem"}),
				    #"PASSO 17 - Coluna condicional - classificacao_duracao" = Table.AddColumn(#"PASSO 16 - Falsos nulos", "classificacao_duracao", each if [duração] = null then null else if [duração] <= 65 then "curta_metragem" else if [duração] > 65 then "longa_metragem" else null),
				    #"PASSO 17 - Reoordenar classificacao_duracao" = Table.ReorderColumns(#"PASSO 17 - Coluna condicional - classificacao_duracao",{"id", "título", "ano", "duração", "classificacao_duracao", "nota_mpa", "nota_imdb", "voto", "orçamento", "receita_bruta_global", "receita_bruta_us_canada", "bruto_lançamento", "diretor", "roteirista", "celebridade", "gênero", "país de origem", "local_de_filmagem", "produtora", "idioma", "indicações", "oscar"}),
				    #"PASSO 19 - Nova coluna condicional - local_de_filmagem2" = Table.AddColumn(#"PASSO 17 - Reoordenar classificacao_duracao", "Personalizar", each if [local_de_filmagem] <> null then [local_de_filmagem] else "Desconhecido"),
				    #"PASSO 19 - Removida local_de_filmagem1" = Table.RemoveColumns(#"PASSO 19 - Nova coluna condicional - local_de_filmagem2",{"local_de_filmagem"}),
				    #"PASSO 19 - Renomear [local_de_filmagem2 -> local_de_filmagem]" = Table.RenameColumns(#"PASSO 19 - Removida local_de_filmagem1",{{"Personalizar", "local_de_filmagem"}})
				in
				    #"PASSO 19 - Renomear [local_de_filmagem2 -> local_de_filmagem]"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

